; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "RoboBackup"
#define MyAppVersion "1.0"
#define MyAppPublisher "LitDev"
#define MyAppExeName "RoboBackup.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6E90FFDA-7F1E-4EF5-8DCE-C3B6DE937159}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=Setup
SetupIconFile=C:\Users\steve\source\repos\RoboBackup\RoboBackup\RoboBackup.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\steve\source\repos\RoboBackup\RoboBackup\bin\Release\net10.0-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\steve\source\repos\RoboBackup\RoboBackup\bin\Release\net10.0-windows\RoboBackup.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\steve\source\repos\RoboBackup\RoboBackup\bin\Release\net10.0-windows\RoboBackup.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\steve\source\repos\RoboBackup\RoboBackup\bin\Release\net10.0-windows\RoboBackup.dll.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\steve\source\repos\RoboBackup\RoboBackup\bin\Release\net10.0-windows\RoboBackup.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\steve\source\repos\RoboBackup\RoboBackup\bin\Release\net10.0-windows\RoboBackup.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

